= Tichu tournament schedule generator

This Python script can be used to create a tournament schedule for the card game Tichu. The number of players and the number of rounds are passed as parameters. The script then creates a corresponding tournament schedule and outputs it either via the command line or as a finished Excel file.
The Excel file contains the corresponding formulae for determining the total Tichu and victory points of each player.

NOTE: The current version only generates tournament schedules for solo tournaments (after every match the players of each team are mixed up again).

== Requirements
* link:https://wiki.python.org/moin/BeginnersGuide/Download[Python]
* link:https://python-poetry.org/docs/#installation[Poetry]

== Installation

.Installation of the dependencies
[source,bash]
----
poetry install
----

== Execution
Local execution of the script on the command line

.Execution of the script with example parameters
[source,bash]
----
poetry run python ./script/main.py -p 6 -r 3
----

[%header,cols="1,1,1,2"] 
|===
|Name
|Short form
|Type
|Description

|--players
|-p
|Value
|Amount of players participating in the tournament

|--rounds
|-r
|Value
|Number of rounds to be played

|--terminal
|-t
|Flag
|If this flag is set the tournament schedule gets printed to the command line instead of generating an Excel file

|--help
|-h
|Flag
|Shows a help message on the command line
|===

NOTE: The number of rounds should be divisible without remainder by the number of players so that all players have the same number of turns.

NOTE: If the number of rounds is less than or equal to the number of players, it is checked that each combination of players does not play together more than once.

== Testing
.Execution of the tests
[source,bash]
----
poetry run python -m pytest ./script/tests.py
----

.Execution of the tests with a coverage report
[source,bash]
----
 poetry run pytest --cov=script --cov-report html:coverage-report  ./script/tests.py
----